### ISSUE TITLE
Does not work on tvOS 12

### ISSUE THREAD

**Issue by visberry** [jvanakker/tvOSBrowser#12]
After following the steps with modifying the availability.h file in the Xcode SDKs for the tvOS Platform, the Xcode build still fails... seems like a compatibility issue with tvOS 12 @steventroughtonsmith

**Comment by digitaltvguy** [comment]
https://github.com/steventroughtonsmith/tvOSBrowser/issues/1

**Comment by alexchandel** [comment]
No.  For tvOS 12, you need to comment out the `API_UNAVAILABLE(tvos)` for `UIDataDetectorTypes` as well.  It's in `/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIDataDetectors.h`.

Just change the ≈22nd line from

```C
} API_UNAVAILABLE(tvos);
```

to

```C
} /* API_UNAVAILABLE(tvos) HACK */;
```

That's in addition to the `__TVOS_UNAVAILABLE_NOTQUITE` and `__TVOS_PROHIBITED_NOTQUITE`.

This issue is closable.

**Comment by jvanakker** [comment]
I actually like the change made by FabioSpacagna, by which you don't need to change Availability.h anymore. See:
https://github.com/FabioSpacagna/tvOSBrowser/tree/master/Browser

Got it working with tvOS 12. I will soon add this to an updated version on my repository as well.

**Comment by jvanakker** [comment]
Updated version compiles with tvOS 12, without issues or any changes required to Availabiity.h. Closing this issue.

**Comment by Brio97131** [comment]
hello got this issue with TVOS12.1
:-1: linker command failed with exit code 1 (use -v to see invocation)
